/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: mysql_events.i

#define SWIGMODULE mysql

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "binlog_event.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_mysql_061405b0074197b1(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_mysql_061405b0074197b1(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_NAME_LEN_mysql_061405b0074197b1() {
  int result;
  intgo _swig_go_result;
  
  
  result = (64*3);
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_MAX_SIZE_LOG_EVENT_STATUS_mysql_061405b0074197b1() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (1U+4+1U+8+1U+1+255+1U+4+1U+6+1U+1+255+1U+2+1U+2+1U+8+1U+4+1U+(16*(1+(64*3))) +3U++1U+16+1+60);
  
  _swig_go_result = result; 
  return _swig_go_result;
}


int64_t *_wrap_SEQ_UNINIT_get_mysql_061405b0074197b1() {
  int64_t result;
  int64_t *_swig_go_result;
  
  
  result = (int64_t)SEQ_UNINIT;
  *(int64_t **)&_swig_go_result = new int64_t(result); 
  return _swig_go_result;
}


intgo _wrap_EVENT_TYPE_PERMUTATION_NUM_get_mysql_061405b0074197b1() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)(unsigned int)EVENT_TYPE_PERMUTATION_NUM;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_do_server_version_split_mysql_061405b0074197b1(_gostring_ _swig_go_0, char *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  unsigned char *arg2 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(unsigned char **)&_swig_go_1; 
  
  do_server_version_split((char const *)arg1,arg2);
  
  free(arg1); 
}


long long _wrap_version_product_mysql_061405b0074197b1(char *_swig_go_0) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned long result;
  long long _swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  
  result = (unsigned long)version_product((unsigned char const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


char *_wrap_checksum_version_split_get_mysql_061405b0074197b1() {
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  
  result = (unsigned char *)(unsigned char *)checksum_version_split;
  *(unsigned char **)&_swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_checksum_version_product_get_mysql_061405b0074197b1() {
  unsigned long result;
  long long _swig_go_result;
  
  
  result = (unsigned long)(unsigned long)checksum_version_product;
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_UNKNOWN_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::UNKNOWN_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_START_EVENT_V3_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::START_EVENT_V3;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_QUERY_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::QUERY_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_STOP_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::STOP_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROTATE_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::ROTATE_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_INTVAR_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::INTVAR_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LOAD_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::LOAD_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_SLAVE_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::SLAVE_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_CREATE_FILE_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::CREATE_FILE_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_APPEND_BLOCK_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::APPEND_BLOCK_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EXEC_LOAD_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::EXEC_LOAD_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_DELETE_FILE_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::DELETE_FILE_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_NEW_LOAD_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::NEW_LOAD_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_RAND_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::RAND_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_USER_VAR_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::USER_VAR_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_FORMAT_DESCRIPTION_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::FORMAT_DESCRIPTION_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_XID_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::XID_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_BEGIN_LOAD_QUERY_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::BEGIN_LOAD_QUERY_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EXECUTE_LOAD_QUERY_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::EXECUTE_LOAD_QUERY_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TABLE_MAP_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::TABLE_MAP_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_PRE_GA_WRITE_ROWS_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::PRE_GA_WRITE_ROWS_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_PRE_GA_UPDATE_ROWS_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::PRE_GA_UPDATE_ROWS_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_PRE_GA_DELETE_ROWS_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::PRE_GA_DELETE_ROWS_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WRITE_ROWS_EVENT_V1_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::WRITE_ROWS_EVENT_V1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_UPDATE_ROWS_EVENT_V1_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::UPDATE_ROWS_EVENT_V1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_DELETE_ROWS_EVENT_V1_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::DELETE_ROWS_EVENT_V1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_INCIDENT_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::INCIDENT_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_HEARTBEAT_LOG_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::HEARTBEAT_LOG_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_IGNORABLE_LOG_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::IGNORABLE_LOG_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROWS_QUERY_LOG_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::ROWS_QUERY_LOG_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WRITE_ROWS_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::WRITE_ROWS_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_UPDATE_ROWS_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::UPDATE_ROWS_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_DELETE_ROWS_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::DELETE_ROWS_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_GTID_LOG_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::GTID_LOG_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ANONYMOUS_GTID_LOG_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::ANONYMOUS_GTID_LOG_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_PREVIOUS_GTIDS_LOG_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::PREVIOUS_GTIDS_LOG_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TRANSACTION_CONTEXT_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::TRANSACTION_CONTEXT_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_VIEW_CHANGE_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::VIEW_CHANGE_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ENUM_END_EVENT_mysql_061405b0074197b1() {
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  
  result = binary_log::ENUM_END_EVENT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ST_CREATED_OFFSET_mysql_061405b0074197b1() {
  int result;
  intgo _swig_go_result;
  
  
  result = (2+50);
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ST_COMMON_HEADER_LEN_OFFSET_mysql_061405b0074197b1() {
  int result;
  intgo _swig_go_result;
  
  
  result = ((2+50) +4);
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_BINLOG_CHECKSUM_ALG_OFF_mysql_061405b0074197b1() {
  binary_log::enum_binlog_checksum_alg result;
  intgo _swig_go_result;
  
  
  result = binary_log::BINLOG_CHECKSUM_ALG_OFF;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_BINLOG_CHECKSUM_ALG_CRC32_mysql_061405b0074197b1() {
  binary_log::enum_binlog_checksum_alg result;
  intgo _swig_go_result;
  
  
  result = binary_log::BINLOG_CHECKSUM_ALG_CRC32;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_BINLOG_CHECKSUM_ALG_ENUM_END_mysql_061405b0074197b1() {
  binary_log::enum_binlog_checksum_alg result;
  intgo _swig_go_result;
  
  
  result = binary_log::BINLOG_CHECKSUM_ALG_ENUM_END;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_BINLOG_CHECKSUM_ALG_UNDEF_mysql_061405b0074197b1() {
  binary_log::enum_binlog_checksum_alg result;
  intgo _swig_go_result;
  
  
  result = binary_log::BINLOG_CHECKSUM_ALG_UNDEF;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


uint32_t *_wrap_checksum_crc32_mysql_061405b0074197b1(uint32_t *_swig_go_0, char *_swig_go_1, long long _swig_go_2) {
  uint32_t arg1 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  size_t arg3 ;
  uint32_t *argp1 ;
  uint32_t result;
  uint32_t *_swig_go_result;
  
  
  argp1 = (uint32_t *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null uint32_t");
  }
  arg1 = (uint32_t)*argp1;
  
  arg2 = *(unsigned char **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  result = binary_log::checksum_crc32(arg1,(unsigned char const *)arg2,arg3);
  *(uint32_t **)&_swig_go_result = new uint32_t(result); 
  return _swig_go_result;
}


intgo _wrap_read_str_at_most_255_bytes_mysql_061405b0074197b1(_gostring_* _swig_go_0, _gostring_ _swig_go_1, _gostring_* _swig_go_2, uint8_t *_swig_go_3) {
  char **arg1 = (char **) 0 ;
  char *arg2 = (char *) 0 ;
  char **arg3 = (char **) 0 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(char ***)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = *(char ***)&_swig_go_2; 
  arg4 = *(uint8_t **)&_swig_go_3; 
  
  result = (int)binary_log::read_str_at_most_255_bytes((char const **)arg1,(char const *)arg2,(char const **)arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_Log_event_footer_get_checksum_alg_mysql_061405b0074197b1(_gostring_ _swig_go_0, long long _swig_go_1) {
  char *arg1 = (char *) 0 ;
  unsigned long arg2 ;
  binary_log::enum_binlog_checksum_alg result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = (unsigned long)_swig_go_1; 
  
  result = (binary_log::enum_binlog_checksum_alg)binary_log::Log_event_footer::get_checksum_alg((char const *)arg1,arg2);
  _swig_go_result = (intgo)result; 
  free(arg1); 
  return _swig_go_result;
}


bool _wrap_Log_event_footer_event_checksum_test_mysql_061405b0074197b1(char *_swig_go_0, long long _swig_go_1, intgo _swig_go_2) {
  unsigned char *arg1 = (unsigned char *) 0 ;
  unsigned long arg2 ;
  binary_log::enum_binlog_checksum_alg arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(unsigned char **)&_swig_go_0; 
  arg2 = (unsigned long)_swig_go_1; 
  arg3 = (binary_log::enum_binlog_checksum_alg)_swig_go_2; 
  
  result = (bool)binary_log::Log_event_footer::event_checksum_test(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


binary_log::Log_event_footer *_wrap_new_Log_event_footer__SWIG_0_mysql_061405b0074197b1() {
  binary_log::Log_event_footer *result = 0 ;
  binary_log::Log_event_footer *_swig_go_result;
  
  
  result = (binary_log::Log_event_footer *)new binary_log::Log_event_footer();
  *(binary_log::Log_event_footer **)&_swig_go_result = (binary_log::Log_event_footer *)result; 
  return _swig_go_result;
}


binary_log::Log_event_footer *_wrap_new_Log_event_footer__SWIG_1_mysql_061405b0074197b1(intgo _swig_go_0) {
  binary_log::enum_binlog_checksum_alg arg1 ;
  binary_log::Log_event_footer *result = 0 ;
  binary_log::Log_event_footer *_swig_go_result;
  
  arg1 = (binary_log::enum_binlog_checksum_alg)_swig_go_0; 
  
  result = (binary_log::Log_event_footer *)new binary_log::Log_event_footer(arg1);
  *(binary_log::Log_event_footer **)&_swig_go_result = (binary_log::Log_event_footer *)result; 
  return _swig_go_result;
}


void _wrap_Log_event_footer_checksum_alg_set_mysql_061405b0074197b1(binary_log::Log_event_footer *_swig_go_0, intgo _swig_go_1) {
  binary_log::Log_event_footer *arg1 = (binary_log::Log_event_footer *) 0 ;
  binary_log::enum_binlog_checksum_alg arg2 ;
  
  arg1 = *(binary_log::Log_event_footer **)&_swig_go_0; 
  arg2 = (binary_log::enum_binlog_checksum_alg)_swig_go_1; 
  
  if (arg1) (arg1)->checksum_alg = arg2;
  
}


intgo _wrap_Log_event_footer_checksum_alg_get_mysql_061405b0074197b1(binary_log::Log_event_footer *_swig_go_0) {
  binary_log::Log_event_footer *arg1 = (binary_log::Log_event_footer *) 0 ;
  binary_log::enum_binlog_checksum_alg result;
  intgo _swig_go_result;
  
  arg1 = *(binary_log::Log_event_footer **)&_swig_go_0; 
  
  result = (binary_log::enum_binlog_checksum_alg) ((arg1)->checksum_alg);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_delete_Log_event_footer_mysql_061405b0074197b1(binary_log::Log_event_footer *_swig_go_0) {
  binary_log::Log_event_footer *arg1 = (binary_log::Log_event_footer *) 0 ;
  
  arg1 = *(binary_log::Log_event_footer **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_Log_event_header_when_set_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0, timeval *_swig_go_1) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  timeval arg2 ;
  timeval *argp2 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  argp2 = (timeval *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null timeval");
  }
  arg2 = (timeval)*argp2;
  
  
  if (arg1) (arg1)->when = arg2;
  
}


timeval *_wrap_Log_event_header_when_get_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  timeval result;
  timeval *_swig_go_result;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  result =  ((arg1)->when);
  *(timeval **)&_swig_go_result = new timeval(result); 
  return _swig_go_result;
}


void _wrap_Log_event_header_type_code_set_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0, intgo _swig_go_1) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  binary_log::Log_event_type arg2 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  arg2 = (binary_log::Log_event_type)_swig_go_1; 
  
  if (arg1) (arg1)->type_code = arg2;
  
}


intgo _wrap_Log_event_header_type_code_get_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  result = (binary_log::Log_event_type) ((arg1)->type_code);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_Log_event_header_unmasked_server_id_set_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0, intgo _swig_go_1) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  unsigned int arg2 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  if (arg1) (arg1)->unmasked_server_id = arg2;
  
}


intgo _wrap_Log_event_header_unmasked_server_id_get_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  result = (unsigned int) ((arg1)->unmasked_server_id);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_Log_event_header_data_written_set_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0, long long _swig_go_1) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  size_t arg2 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  if (arg1) (arg1)->data_written = arg2;
  
}


long long _wrap_Log_event_header_data_written_get_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  result =  ((arg1)->data_written);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_Log_event_header_log_pos_set_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0, long long _swig_go_1) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  unsigned long long arg2 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  arg2 = (unsigned long long)_swig_go_1; 
  
  if (arg1) (arg1)->log_pos = arg2;
  
}


long long _wrap_Log_event_header_log_pos_get_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  unsigned long long result;
  long long _swig_go_result;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  result = (unsigned long long) ((arg1)->log_pos);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_Log_event_header_flags_set_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0, uint16_t *_swig_go_1) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  uint16_t arg2 ;
  uint16_t *argp2 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  argp2 = (uint16_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null uint16_t");
  }
  arg2 = (uint16_t)*argp2;
  
  
  if (arg1) (arg1)->flags = arg2;
  
}


uint16_t *_wrap_Log_event_header_flags_get_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  uint16_t result;
  uint16_t *_swig_go_result;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  result =  ((arg1)->flags);
  *(uint16_t **)&_swig_go_result = new uint16_t(result); 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_new_Log_event_header__SWIG_0_mysql_061405b0074197b1(intgo _swig_go_0) {
  binary_log::Log_event_type arg1 ;
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  arg1 = (binary_log::Log_event_type)_swig_go_0; 
  
  result = (binary_log::Log_event_header *)new binary_log::Log_event_header(arg1);
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_new_Log_event_header__SWIG_1_mysql_061405b0074197b1() {
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  
  result = (binary_log::Log_event_header *)new binary_log::Log_event_header();
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_new_Log_event_header__SWIG_2_mysql_061405b0074197b1(_gostring_ _swig_go_0, uint16_t *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  uint16_t arg2 ;
  uint16_t *argp2 ;
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  argp2 = (uint16_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null uint16_t");
  }
  arg2 = (uint16_t)*argp2;
  
  
  result = (binary_log::Log_event_header *)new binary_log::Log_event_header((char const *)arg1,arg2);
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  free(arg1); 
  return _swig_go_result;
}


void _wrap_delete_Log_event_header_mysql_061405b0074197b1(binary_log::Log_event_header *_swig_go_0) {
  binary_log::Log_event_header *arg1 = (binary_log::Log_event_header *) 0 ;
  
  arg1 = *(binary_log::Log_event_header **)&_swig_go_0; 
  
  delete arg1;
  
}


intgo _wrap_Binary_log_event_LOG_EVENT_TYPES_Binary_log_event_mysql_061405b0074197b1() {
  int result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::LOG_EVENT_TYPES;
  
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_QUERY_HEADER_MINIMAL_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::QUERY_HEADER_MINIMAL_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_QUERY_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::QUERY_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_STOP_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::STOP_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_LOAD_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::LOAD_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_START_V3_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::START_V3_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROTATE_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::ROTATE_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_INTVAR_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::INTVAR_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_CREATE_FILE_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::CREATE_FILE_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_APPEND_BLOCK_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::APPEND_BLOCK_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EXEC_LOAD_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::EXEC_LOAD_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_DELETE_FILE_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::DELETE_FILE_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_NEW_LOAD_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::NEW_LOAD_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_RAND_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::RAND_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_USER_VAR_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::USER_VAR_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_FORMAT_DESCRIPTION_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::FORMAT_DESCRIPTION_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_XID_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::XID_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_BEGIN_LOAD_QUERY_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::BEGIN_LOAD_QUERY_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROWS_HEADER_LEN_V1_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::ROWS_HEADER_LEN_V1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TABLE_MAP_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::TABLE_MAP_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EXECUTE_LOAD_QUERY_EXTRA_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::EXECUTE_LOAD_QUERY_EXTRA_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EXECUTE_LOAD_QUERY_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::EXECUTE_LOAD_QUERY_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_INCIDENT_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::INCIDENT_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_HEARTBEAT_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::HEARTBEAT_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_IGNORABLE_HEADER_LEN_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::IGNORABLE_HEADER_LEN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROWS_HEADER_LEN_V2_Binary_log_event_mysql_061405b0074197b1() {
  binary_log::Binary_log_event::enum_post_header_length result;
  intgo _swig_go_result;
  
  
  result = binary_log::Binary_log_event::ROWS_HEADER_LEN_V2;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_Binary_log_event_print_event_info_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0, std::ostream *_swig_go_1) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  std::ostream *arg2 = 0 ;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  arg2 = *(std::ostream **)&_swig_go_1; 
  
  (arg1)->print_event_info(*arg2);
  
}


void _wrap_Binary_log_event_print_long_info_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0, std::ostream *_swig_go_1) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  std::ostream *arg2 = 0 ;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  arg2 = *(std::ostream **)&_swig_go_1; 
  
  (arg1)->print_long_info(*arg2);
  
}


void _wrap_delete_Binary_log_event_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  
  delete arg1;
  
}


intgo _wrap_Binary_log_event_get_event_type_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  enum binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  
  result = (enum binary_log::Log_event_type)((binary_log::Binary_log_event const *)arg1)->get_event_type();
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_Binary_log_event_header__SWIG_0_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  
  result = (binary_log::Log_event_header *)((binary_log::Binary_log_event const *)arg1)->header();
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_Binary_log_event_header__SWIG_1_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  
  result = (binary_log::Log_event_header *)(arg1)->header();
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  return _swig_go_result;
}


binary_log::Log_event_footer *_wrap_Binary_log_event_footer__SWIG_0_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  binary_log::Log_event_footer *result = 0 ;
  binary_log::Log_event_footer *_swig_go_result;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  
  result = (binary_log::Log_event_footer *)((binary_log::Binary_log_event const *)arg1)->footer();
  *(binary_log::Log_event_footer **)&_swig_go_result = (binary_log::Log_event_footer *)result; 
  return _swig_go_result;
}


binary_log::Log_event_footer *_wrap_Binary_log_event_footer__SWIG_1_mysql_061405b0074197b1(binary_log::Binary_log_event *_swig_go_0) {
  binary_log::Binary_log_event *arg1 = (binary_log::Binary_log_event *) 0 ;
  binary_log::Log_event_footer *result = 0 ;
  binary_log::Log_event_footer *_swig_go_result;
  
  arg1 = *(binary_log::Binary_log_event **)&_swig_go_0; 
  
  result = (binary_log::Log_event_footer *)(arg1)->footer();
  *(binary_log::Log_event_footer **)&_swig_go_result = (binary_log::Log_event_footer *)result; 
  return _swig_go_result;
}


binary_log::Unknown_event *_wrap_new_Unknown_event__SWIG_0_mysql_061405b0074197b1() {
  binary_log::Unknown_event *result = 0 ;
  binary_log::Unknown_event *_swig_go_result;
  
  
  result = (binary_log::Unknown_event *)new binary_log::Unknown_event();
  *(binary_log::Unknown_event **)&_swig_go_result = (binary_log::Unknown_event *)result; 
  return _swig_go_result;
}


binary_log::Unknown_event *_wrap_new_Unknown_event__SWIG_1_mysql_061405b0074197b1(_gostring_ _swig_go_0, binary_log::Format_description_event *_swig_go_1) {
  char *arg1 = (char *) 0 ;
  binary_log::Format_description_event *arg2 = (binary_log::Format_description_event *) 0 ;
  binary_log::Unknown_event *result = 0 ;
  binary_log::Unknown_event *_swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(binary_log::Format_description_event **)&_swig_go_1; 
  
  result = (binary_log::Unknown_event *)new binary_log::Unknown_event((char const *)arg1,(binary_log::Format_description_event const *)arg2);
  *(binary_log::Unknown_event **)&_swig_go_result = (binary_log::Unknown_event *)result; 
  free(arg1); 
  return _swig_go_result;
}


void _wrap_Unknown_event_print_event_info_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0, std::ostream *_swig_go_1) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  std::ostream *arg2 = 0 ;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  arg2 = *(std::ostream **)&_swig_go_1; 
  
  (arg1)->print_event_info(*arg2);
  
}


void _wrap_Unknown_event_print_long_info_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0, std::ostream *_swig_go_1) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  std::ostream *arg2 = 0 ;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  arg2 = *(std::ostream **)&_swig_go_1; 
  
  (arg1)->print_long_info(*arg2);
  
}


void _wrap_delete_Unknown_event_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  
  delete arg1;
  
}


intgo _wrap_Unknown_event_get_event_type_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  enum binary_log::Log_event_type result;
  intgo _swig_go_result;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  
  binary_log::Binary_log_event *swig_b0 = (binary_log::Binary_log_event *)arg1;
  result = (enum binary_log::Log_event_type)((binary_log::Binary_log_event const *)swig_b0)->get_event_type();
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_Unknown_event_header__SWIG_0_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  
  binary_log::Binary_log_event *swig_b0 = (binary_log::Binary_log_event *)arg1;
  result = (binary_log::Log_event_header *)((binary_log::Binary_log_event const *)swig_b0)->header();
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  return _swig_go_result;
}


binary_log::Log_event_header *_wrap_Unknown_event_header__SWIG_1_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  binary_log::Log_event_header *result = 0 ;
  binary_log::Log_event_header *_swig_go_result;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  
  binary_log::Binary_log_event *swig_b0 = (binary_log::Binary_log_event *)arg1;
  result = (binary_log::Log_event_header *)(swig_b0)->header();
  *(binary_log::Log_event_header **)&_swig_go_result = (binary_log::Log_event_header *)result; 
  return _swig_go_result;
}


binary_log::Log_event_footer *_wrap_Unknown_event_footer__SWIG_0_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  binary_log::Log_event_footer *result = 0 ;
  binary_log::Log_event_footer *_swig_go_result;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  
  binary_log::Binary_log_event *swig_b0 = (binary_log::Binary_log_event *)arg1;
  result = (binary_log::Log_event_footer *)((binary_log::Binary_log_event const *)swig_b0)->footer();
  *(binary_log::Log_event_footer **)&_swig_go_result = (binary_log::Log_event_footer *)result; 
  return _swig_go_result;
}


binary_log::Log_event_footer *_wrap_Unknown_event_footer__SWIG_1_mysql_061405b0074197b1(binary_log::Unknown_event *_swig_go_0) {
  binary_log::Unknown_event *arg1 = (binary_log::Unknown_event *) 0 ;
  binary_log::Log_event_footer *result = 0 ;
  binary_log::Log_event_footer *_swig_go_result;
  
  arg1 = *(binary_log::Unknown_event **)&_swig_go_0; 
  
  binary_log::Binary_log_event *swig_b0 = (binary_log::Binary_log_event *)arg1;
  result = (binary_log::Log_event_footer *)(swig_b0)->footer();
  *(binary_log::Log_event_footer **)&_swig_go_result = (binary_log::Log_event_footer *)result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

